config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :my_questions, only: [:index]
  
  resources :questions do
    resources :favorites, only: [:create, :destroy]
    resources :likes,     only: [:create, :destroy] 
    resources :answers,   only: [:create, :destroy]
  end
  
  resources :answers, only: [] do 
    resources :comments, except: [:index, :show, :new]
  end

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  root 'questions#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :answer
  belongs_to :user

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_answer
  before_action :find_comment, except: [:create]

  def create
    @comment      = @answer.comments.new(comment_params)
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        flash.now[:notice] = "Comment posted!"
        format.html { redirect_to @answer.question, notice: "Comment posted!" }
        format.js { render }
      else
        flash.now[:alert] = "Comment couldn't be posted."
        format.html { redirect_to @answer.question, alert: "Comment wasn't posted." }
        format.js   { render }
      end
    end
  end

  def edit
  end

  def update
    if @comment.update_attributes(comment_params)
      redirect_to @answer.question, notice: "Comment updated!"
    else
      flash.now[:alert] = "Something went wrong updating this comment"
      render :edit
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @answer.question, notice: "Comment deleted" }
      format.js { render }
    end
  end


  private

  def find_answer
    @answer = Answer.find params[:answer_id]
  end

  def find_comment
    @comment = @answer.comments.find params[:id]
  end

  def comment_params
    params.require(:comment).permit(:body)
  end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
.col-xs-11.col-xs-offset-1{id: dom_id(comment)}
  %hr
  = comment.body
  = formatted_date(comment.created_at)
  = link_to "edit", edit_answer_comment_path(answer, comment), class: "btn btn-info btn-xs"
  = button_to "Delete", [answer, comment], method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-xs", remote: true

app/views/comments/create.js.haml
- if @comment.errors.any?
  $(".flash-messages").html("#{j render '/layouts/flash_messages'}");
  $("##{dom_id(@answer)} .comments-errors").html("#{j render partial: '/shared/standard_errors', locals: { object: @comment } }");
- else
  $(".flash-messages").html("#{j render '/layouts/flash_messages'}");
  $("##{dom_id(@answer)} .comments").prepend("#{ j render partial: "comments/comment", locals: { answer: @answer, comment: @comment } }");
  $("##{dom_id(@answer)} #new-comment").val("");
  $("##{dom_id(@answer)} .comments-errors").html("");

app/views/comments/destroy.js.haml
$("##{dom_id(@comment)}").fadeOut(1000, function(){ $(this).remove() });

app/views/comments/edit.html.haml
%h1 Edit this guy

= form_for [@answer, @comment] do |f|
  = f.text_area :body
  = f.submit "Update Comment"