config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :my_questions, only: [:index]
  
  resources :questions do
    resources :favorites, only: [:create, :destroy]
    resources :likes,     only: [:create, :destroy] 
    resources :answers,   only: [:create, :destroy]
  end
  
  resources :answers, only: [] do 
    resources :comments, except: [:index, :show, :new]
  end

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  root 'questions#index'

end

app/controllers/my_questions_controller.rb
class MyQuestionsController < ApplicationController
  
  before_action :authenticate_user!

  def index
    @my_questions = current_user.questions
  end


  private



end

app/helpers/my_questions_helper.rb
module MyQuestionsHelper
end

app/views/my_questions/index.html.haml
%h1 
  #{current_user.name_display}'s Questions

- @my_questions.each do |question|
  .row{ id: dom_id(question)}
    .well.col-xs-12.col-md-10.col-md-offset-1
      %h2
        = link_to question.title, question
      %p= question.description
      .row
        .col-md-2.col-md-offset-10.col-xs-6.col-xs-offset-6
          = link_to "Delete", question_path(question), method: :delete, class: "btn btn-danger", remote: true, data: { confirm: "Are you sure?" }
          = link_to "Edit", edit_question_path(question.id), class: "btn btn-info", data: { toggle: "modal", target: "#editQuestion" }, remote: true

#editQuestion.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "editQuesitonLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} &#215;
        %h4#myModalLabel.modal-title Edit Question
      #edit-errors
      .modal-body.edit-modal
      .modal-footer